### PR TITLE
Update to version 1.2.2

### PR DESCRIPTION
**Pull request by gottcode**

### CODE REVIEW

**Comment by yselkowitz** [comment]
Hi @gottcode it seems this never shipped on flathub.

**Comment by gottcode** [comment]
> Hi @gottcode it seems this never shipped on flathub.

Unfortunately, I have no idea why it wasn't shipped to Flathub and no clue what to do about it. It passed the checks, so it should have automatically shipped like all my other projects.

**Comment by yselkowitz** [comment]
I'm not that familiar with the process, but does https://buildbot.flathub.org/#/apps/org.gottcode.Hexalate or https://buildbot.flathub.org/#/builders/6/builds/16712 show anything pertinent?  If not, perhaps just kick off a rebuild or update (e.g. is 1.2.3 forthcoming)?

**Comment by gottcode** [comment]
@yselkowitz Nothing looks amiss in those logs. I'm not sure how to kick off a rebuild, and there aren't any updates to Hexalate anytime soon. The next update is switching to Qt 6.5 when that comes out later in the year.

**Pull request merged**
